baseURL: "https://nchlswhttkr.com/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true
pygmentsCodeFences: true

disableKinds:
  - "taxonomyTerm" # I don't currently use categories/tags

params:
  me:
    name: "Nicholas Whittaker"
    username: "nchlswhttkr"
  identities:
    - prompt: "Find this website"
      icon: "/media/icons/website.svg"
      link: "/"
    - prompt: "Subscribe to an RSS feed"
      icon: "/media/icons/rss.svg"
      link: "/index.xml"
    - prompt: "Send me an email"
      icon: "/media/icons/email.svg"
      link: "mailto:nchlswhttkr@gmail.com"
    - prompt: "Find me on GitHub"
      icon: "/media/icons/github.svg"
      link: "https://github.com/nchlswhttkr/"
    - prompt: "Find me on GitLab"
      icon: "/media/icons/gitlab.svg"
      link: "https://gitlab.com/nchlswhttkr/"
    - prompt: "Find me on Twitter"
      icon: "/media/icons/twitter.svg"
      link: "https://twitter.com/nchlswhttkr/"
    - prompt: "Find me on LinkedIn"
      icon: "/media/icons/linkedin.svg"
      link: "https://linkedin.com/in/nchlswhttkr/"
    - prompt: "Verify me on Keybase"
      icon: "/media/icons/keybase.svg"
      link: "https://keybase.io/nchlswhttkr/"
