baseURL: "https://nicholas.cloud/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true
enableRobotsTXT: true

taxonomies:
    tag: tags

# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # style: vs
        noClasses: false

params:
    color: "#555d25"
