baseURL: "https://nicholas.cloud/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true
buildFuture: true

disableKinds:
    - "taxonomyTerm" # I don't currently use categories/tags

# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # style: vs
        noClasses: false
