baseURL: "https://nchlswhttkr.com/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true

params:
  me:
    name: Nicholas Whittaker
    email: nchlswhttkr+enquiries@gmail.com
    username: nchlswhttkr
  identities:
    - site: Twitter
      profile: https://twitter.com/nchlswhttkr
      username: nchlswhttkr
    - site: Github
      profile: https://github.com/nchlswhttkr
      username: nchlswhttkr
    - site: Bitbucket
      profile: https://bitbucket.com/nchlswhttkr
      username: nchlswhttkr
    - site: GitLab
      profile: https://gitlab.com/nchlswhttkr
      username: nchlswhttkr
    - site: LinkedIn
      profile: https://linkedin.com/in/nchlswhttkr/
      username: nchlswhttkr
    # - site: Facebook
    # - site: npm
    # - site: Travis
    # - site: Medium
