baseURL: "https://nchlswhttkr.com/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true

disableKinds:
  - "taxonomyTerm"

params:
  me:
    name: "Nicholas Whittaker"
    username: "nchlswhttkr"
  identities:
    - site: "Email"
      link: "mailto:nchlswhttkr@gmail.com"
    - site: "LinkedIn"
      link: "https://linkedin.com/in/nchlswhttkr/"
    - site: "Twitter"
      link: "https://twitter.com/nchlswhttkr/"
    - site: "Github"
      link: "https://github.com/nchlswhttkr/"
    - site: "GitLab"
      link: "https://gitlab.com/nchlswhttkr/"
    - site: "Bitbucket"
      link: "https://bitbucket.org/nchlswhttkr/"
    - site: "Medium"
      link: "https://medium.com/@nchlswhttkr/"
    # - site: "Soundcloud"
    # - site: "Facebook"
    # - site: "Twitch"
    # - site: "npm"
    # - site: "Travis"
