baseURL: "https://nchlswhttkr.gitlab.io/"
languageCode: "en-us"
title: "Nicholas Whittaker"
enableEmoji: true

params:
  me:
    name: Nicholas Whittaker
    email: nchlswhttkr+enquiries@gmail.com
    username: nchlswhttkr
  identities:
    - site: Twitter
      profile: https://twitter.com/nchlswhttkr
    - site: Github
      profile: https://github.com/nchlswhttkr
    - site: Bitbucket
      profile: https://bitbucket.com/nchlswhttkr
    - site: GitLab
      profile: https://gitlab.com/nchlswhttkr
    - site: LinkedIn
      profile: https://linkedin.com/in/nchlswhttkr/
    # - site: Facebook
    # - site: npm
    # - site: Travis
    # - site: Medium
    # - site: Soundcloud
