steps:
  - label: ":hugo:"
    command: hugo
  - wait
  - label: ":shipit:"
    branches: master
    command:
      - hugo
      - rsync -a --chown :nchlswhttkr.com --delete $PWD/public/ /home/nchlswhttkr/nchlswhttkr.com
