steps:
  - label: ":hugo:"
    agents:
      deploy-nchlswhttkr.com: true
    command: hugo
  - wait
  - label: ":shipit:"
    branches: master
    agents:
      deploy-nchlswhttkr.com: true
    command:
      - hugo
      - rsync -a --delete $PWD/public/ nchlswhttkr@$DEPLOYMENT_IP:~/nchlswhttkr.com
