# prettier-ignore
steps:
  - label: ":shipit:"
    branches: master
    agents:
      deploy-personal-website: true
    command: .buildkite/build.sh
  - wait
  - label: ":rolled_up_newspaper:"
    branches: master
    agents:
      deploy-personal-website: true
    command: .buildkite/trigger-newsletter-if-new-issue.sh
