steps:
  - label: ":shipit:"
    branches: master
    agents:
      deploy-personal-website: true
    command:
      - hugo --minify --cleanDestinationDir
      - rsync --recursive --verbose --itemize-changes --checksum --delete $PWD/public/ /var/www/nicholas.cloud
  - wait
  - label: ":rolled_up_newspaper:"
    branches: master
    agents:
      deploy-personal-website: true
    command: .buildkite/trigger-newsletter-if-new-issue.sh
