# prettier-ignore
steps:
  - label: ':shipit:'
    if: 'build.branch == "main"'
    agents:
      website: nicholas.cloud
    command: .buildkite/build.sh
  - wait
  - label: ':rolled_up_newspaper:'
    if: 'build.branch == "main" && build.source != "schedule"'
    agents:
      website: nicholas.cloud
    command: .buildkite/trigger-newsletter-if-new-issue.sh
