# prettier-ignore
steps:
  - label: ':hugo:'
    agents:
      deploy-personal-website: true
    command: hugo
  - wait
  - label: ':shipit:'
    if: 'build.branch == "main"'
    agents:
      deploy-personal-website: true
    command: .buildkite/build.sh
  - wait
  - label: ':rolled_up_newspaper:'
    if: 'build.branch == "main" && build.source != "schedule"'
    agents:
      deploy-personal-website: true
    command: .buildkite/trigger-newsletter-if-new-issue.sh
