steps:
  - label: ":hugo:"
    agents:
      deploy-personal-website: true
    command: hugo
  - wait
  - label: ":shipit:"
    branches: master
    agents:
      deploy-personal-website: true
    command:
      - hugo --minify
      - rsync -a --delete $PWD/public/ nicholas@$DEPLOYMENT_IP:/var/www/nicholas.cloud
  - wait
  - label: ":rolled_up_newspaper:"
    # branches: master
    agents:
      deploy-personal-website: true
    command: "source .buildkite/trigger-newsletter-if-new-issue.sh"
