name: Build & Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.pkg.github.com/nchlswhttkr/hugo-compress/hugo-compress:latest
      - uses: ./.github/push-to-master-action
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
