name: Build & Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: 'sed -i ''s;baseURL:.*;baseURL: "https://nchlswhttkr.github.io";'' config.yml'
            - uses: docker://registry.gitlab.com/pages/hugo:latest
            - uses: ./.github/push-to-github-pages
              env:
                  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
