name: Build & Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sed -i "s;https://nchlswhttkr.com;https://nchlswhttkr.github.io;" config.yml
      - uses: docker://registry.gitlab.com/pages/hugo:latest
      - uses: ./.github/push-to-github-pages
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
